- hosts: webservers
  remote_user: root
  vars:
  - package: httpd
  - service: httpd
  tasks:
  - name: install httpd package
    yum: name={{package}} state=latest
  - name: install configuration file for httpd
    copy: src=/root/templates/httpd.conf dest=/etc/httpd/conf/httpd.conf  #error 应该使用jinja2
    notify:
    - restart httpd
  - name: start httpd service
    service: enabled=true name={{service}} state=started
  handlers:
  - name: restart httpd
    service: name={{service}} state=restarted
